### PR TITLE
bug/FWS-67/Sign-up-Database-Bug

### PR DESCRIPTION
**Pull request by Eli293**
JIRA: link to jira ticket
https://champlainsaintlambert.atlassian.net/browse/FWS-67 
## Context:
This ticket is about a bug with the sign up function that adds a user to the database where it would add too many users at a time.

## Changes

- Fixed Sign-up bug

### CODE REVIEW

**Review by AlexeiTimbro — APPROVED** [review]
Here is a smootch 😙 for all your hard work Elias.

**Comment by Eli293** [comment]
> Here is a smootch 😙 for all your hard work Elias.

Get out of my PR weirdo, Im calling my mom!

**Comment by AlexeiTimbro** [comment]
> > Here is a smootch 😙 for all your hard work Elias.
> 
> Get out of my PR weirdo, Im calling my mom!

AHAHAHHAHAHAHAHHAHAHA

**Review by Abdur-Siddiqui — APPROVED** [review]
Looks good, Elias I know you want that smouch from Alexei.

**Pull request merged**
